-- AlterEnum
ALTER TYPE "ScamEventType" ADD VALUE IF NOT EXISTS 'FLOW_TRACE';
ALTER TYPE "ScamEventType" ADD VALUE IF NOT EXISTS 'PLATFORM_INTERACTION';
ALTER TYPE "ScamEventType" ADD VALUE IF NOT EXISTS 'FLOW_TO_NEW_LAUNCH';
